baseURL = "https://www.presslabs.org/silver/docs/"
languageCode = "en-us"
title = "Silver Documentation"
summaryLength = 15
metaDataFormat = "yaml"
theme = "presslabs"
enableRobotsTXT = true
enableGitInfo = true
pygmentsCodeFences = true
pygmentsOptions = ""
pygmentsUseClasses = true
pygmentsUseClassic = false
pygmentsStyle = "github"

[params]
  site_url = "https://www.presslabs.com/"
  legal_url = "https://www.presslabs.com/legal"
  breadcrumbs_root = "Presslabs DOCS"
  quick_start = true
  quick_start_link = "getting-started/"
  logo_text = "DOCS"
  search_placeholder = "Search docs"
  footer_menu = true
  footer_menu_title = "DOCUMENTATION"
  title = "Welcome to Presslabs Documentation!"
  description = "We’re glad to have you on board! We’re here to help you to better manage your WordPress site, and to deliver the best viewing experience for your users."
  release = "3.0.0"
  # debug = true
  algolia_search = true
  algolia_appId = "0TS6NFHDBC"
  algolia_apiKey = "d2a5958e9769691faac2c1c041b1ba31"
  algolia_indexName = "Silver"
  algolia_currentLanguageOnly = true
  images = ["images/docs.png"]

[params.algolia]
  vars = ["title", "description", "summary", "content", "date", "lastmod", "permalink", "lvl0", "lvl1", "url"]
  params = ["categories", "keywords"]

[blackfriday]
  angledQuotes = true
  extensions = ["hardLineBreak"]
  sourceRelativeLinks = true
  fractions = false
  plainIDAnchors = true

[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[outputs]
  home = [ "HTML", "RSS", "JSON", "Algolia" ]

[taxonomies]
  category = "categories"

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "keywords"
  weight = 150

[[menu.global]]
  name = "Getting Started"
  weight = 1
  identifier = "getting-started"
  url = "/getting-started/"

[[menu.global]]
  name = "Silver"
  weight = 2
  identifier = "silver"
  url = "/silver/"

[[menu.docs]]
  name = "Getting Started"
  weight = 1
  identifier = "getting-started"

[[menu.docs]]
  name = "Silver"
  weight = 2
  identifier = "silver"

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"
