site_name: silver
site_url: https://presslabs.org/silver/
repo_url: https://github.com/silverapp/silver.git
repo_name: silver
site_author: Presslabs
theme_dir: docs-theme
docs_dir: documentation
site_dir: compiled_docs
extra:
  home_url: https://www.presslabs.com
markdown_extensions:
    - admonition
    - toc:
        baselevel: 1
pages:
    - General: 'index.md'
    - Resources: 'resources.md'
    - Customers: 'customers.md'
    - Providers: 'providers.md'
    - Plans: 'plans.md'
    - Subscriptions: 'subscriptions.md'
    - Invoices: 'invoices.md'
    - Proformas: 'proformas.md'
    - How Automatic Invoices Are Generated: 'how-automatic-invoices-are-generated.md'
    - Transactions: 'transactions.md'
    - Payment Processors: 'payment-processors.md'
    - Payment Methods: 'payment-methods.md'
    - API: 'api.md'
